OPENMOJI_LOGOS = {
    "Fútbol": "https://openmoji.org/data/color/svg/26BD.svg",
    "Fútbol Sala": "https://openmoji.org/data/color/svg/26BD.svg",
    "Fútbol Playa": "https://openmoji.org/data/color/svg/26BD.svg",
    "Baloncesto": "https://openmoji.org/data/color/svg/1F3C0.svg",
    "Béisbol": "https://openmoji.org/data/color/svg/26BE.svg",
    "Sóftbol": "https://openmoji.org/data/color/svg/26BE.svg",
    "Fútbol Americano": "https://openmoji.org/data/color/svg/1F3C8.svg",
    "Fútbol Canadiense": "https://openmoji.org/data/color/svg/1F3C8.svg",
    "Rugby": "https://openmoji.org/data/color/svg/1F3C9.svg",
    "Hockey sobre Hielo": "https://openmoji.org/data/color/svg/1F3D2.svg",
    "Hockey sobre Hierba": "https://openmoji.org/data/color/svg/1F3D1.svg",
    "Críquet": "https://openmoji.org/data/color/svg/1F3CF.svg",
    "Voleibol": "https://openmoji.org/data/color/svg/1F3D0.svg",
    "Vóley Playa": "https://openmoji.org/data/color/svg/1F3D0.svg",
    "Balonmano": "https://openmoji.org/data/color/svg/1F93E.svg",
    "Tenis": "https://openmoji.org/data/color/svg/1F3BE.svg",
    "Bádminton": "https://openmoji.org/data/color/svg/1F3F8.svg",
    "Tenis de Mesa": "https://openmoji.org/data/color/svg/1F3D3.svg",
    "Golf": "https://openmoji.org/data/color/svg/26F3.svg",
    "Atletismo": "https://openmoji.org/data/color/svg/1F3C3.svg",
    "Natación": "https://openmoji.org/data/color/svg/1F3CA.svg",
    "Natación Artística": "https://openmoji.org/data/color/svg/1F3CA.svg",
    "Saltos": "https://openmoji.org/data/color/svg/1F3C2.svg",
    "Waterpolo": "https://openmoji.org/data/color/svg/1F3CA.svg",
    "Natación en Aguas Abiertas": "https://openmoji.org/data/color/svg/1F3CA.svg",
    "Ciclismo en Ruta": "https://openmoji.org/data/color/svg/1F6B4.svg",
    "Ciclismo en Pista": "https://openmoji.org/data/color/svg/1F6B4.svg",
    "Ciclismo de Montaña": "https://openmoji.org/data/color/svg/1F6B4.svg",
    "BMX": "https://openmoji.org/data/color/svg/1F6B2.svg",
    "Ciclocrós": "https://openmoji.org/data/color/svg/1F6B2.svg",
    "Gimnasia Artística": "https://openmoji.org/data/color/svg/1F938.svg",
    "Gimnasia Rítmica": "https://openmoji.org/data/color/svg/1F938.svg",
    "Gimnasia en Trampolín": "https://openmoji.org/data/color/svg/1F938.svg",
    "Gimnasia Acrobática": "https://openmoji.org/data/color/svg/1F938.svg",
    "Gimnasia Aeróbica": "https://openmoji.org/data/color/svg/1F938.svg",
    "Boxeo": "https://openmoji.org/data/color/svg/1F94A.svg",
    "Judo": "https://openmoji.org/data/color/svg/1F94B.svg",
    "Taekwondo": "https://openmoji.org/data/color/svg/1F94B.svg",
    "Lucha": "https://openmoji.org/data/color/svg/1F93C.svg",
    "Esgrima": "https://openmoji.org/data/color/svg/1F5E1.svg",
    "Karate": "https://openmoji.org/data/color/svg/1F94B.svg",
    "Artes Marciales Mixtas": "https://openmoji.org/data/color/svg/1F94B.svg",
    "Kickboxing": "https://openmoji.org/data/color/svg/1F94A.svg",
    "Muay Thai": "https://openmoji.org/data/color/svg/1F94A.svg",
    "Sumo": "https://openmoji.org/data/color/svg/1F93C.svg",
    "Kendo": "",
    "Aikido": "",
    "Jiu-Jitsu Brasileño": "",
    "Sambo": "",
    "Savate": "",
    "Esquí Alpino": "https://openmoji.org/data/color/svg/1F3C2.svg",
    "Esquí de Fondo": "https://openmoji.org/data/color/svg/1F3C2.svg",
    "Saltos de Esquí": "https://openmoji.org/data/color/svg/1F3C2.svg",
    "Combinada Nórdica": "https://openmoji.org/data/color/svg/1F3C2.svg",
    "Biatlón": "",
    "Snowboard": "https://openmoji.org/data/color/svg/1F3C2.svg",
    "Esquí Acrobático / Estilo Libre": "https://openmoji.org/data/color/svg/1F3C2.svg",
    "Patinaje Artístico sobre Hielo": "",
    "Patinaje de Velocidad sobre Hielo": "",
    "Patinaje de Velocidad sobre Hielo en Pista Corta": "",
    "Curling": "https://openmoji.org/data/color/svg/1F94C.svg",
    "Bobsleigh": "",
    "Skeleton": "",
    "Luge": "",
    "Esquí de Montaña": "https://openmoji.org/data/color/svg/1F3C2.svg",
    "Surf": "https://openmoji.org/data/color/svg/1F3C4.svg",
    "Windsurf": "",
    "Kitesurf / Kiteboard": "",
    "Vela": "https://openmoji.org/data/color/svg/26F5.svg",
    "Remo": "https://openmoji.org/data/color/svg/1F6A3.svg",
    "Piragüismo / Canotaje": "https://openmoji.org/data/color/svg/1F6F6.svg",
    "Kayak Polo": "https://openmoji.org/data/color/svg/1F6F6.svg",
    "Bote Dragón": "",
    "Motonáutica": "",
    "Esquí Acuático": "",
    "Wakeboard": "",
    "Pesca Deportiva": "https://openmoji.org/data/color/svg/1F3A3.svg",
    "Apnea / Buceo Libre": "",
    "Hockey Subacuático": "",
    "Rugby Subacuático": "",
    "Fórmula 1": "https://openmoji.org/data/color/svg/1F3CE.svg",
    "Rally": "https://openmoji.org/data/color/svg/1F698.svg",
    "Carreras de Resistencia": "https://openmoji.org/data/color/svg/1F3CE.svg",
    "Turismos": "https://openmoji.org/data/color/svg/1F698.svg",
    "NASCAR": "https://openmoji.org/data/color/svg/1F3CE.svg",
    "IndyCar Series": "https://openmoji.org/data/color/svg/1F3CE.svg",
    "Fórmula E": "https://openmoji.org/data/color/svg/1F3CE.svg",
    "Karting": "https://openmoji.org/data/color/svg/1F3CE.svg",
    "Drifting": "",
    "Carreras de Aceleración": "",
    "MotoGP": "https://openmoji.org/data/color/svg/1F3CD.svg",
    "Superbikes": "https://openmoji.org/data/color/svg/1F3CD.svg",
    "Motocross": "https://openmoji.org/data/color/svg/1F3CD.svg",
    "Enduro": "https://openmoji.org/data/color/svg/1F3CD.svg",
    "Speedway": "https://openmoji.org/data/color/svg/1F3CD.svg",
    "Trial": "",
    "Carreras de Resistencia (Endurance Racing - Motos)": "",
    "Tiro con Arco": "https://openmoji.org/data/color/svg/1F3F9.svg",
    "Tiro Deportivo": "",
    "Billar": "https://openmoji.org/data/color/svg/1F3B1.svg",
    "Dardos": "https://openmoji.org/data/color/svg/1F3AF.svg",
    "Bolos": "https://openmoji.org/data/color/svg/1F3B3.svg",
    "Petanca": "",
    "Bochas / Bocce": "",
    "Skateboarding": "https://openmoji.org/data/color/svg/1F6F9.svg",
    "Escalada Deportiva": "https://openmoji.org/data/color/svg/1F9D7.svg",
    "Parkour / Freerunning": "",
    "Slackline": "",
    "Salto BASE": "",
    "Paracaidismo": "",
    "Ala Delta": "",
    "Parapente": "",
    "Raids de Aventura": "",
    "Carreras de Obstáculos": "",
    "Sandboarding / Surf de Arena": "",
    "Zorbing / Esferismo": "",
    "Street Luge": "",
    "Patinaje en Línea Agresivo": "",
    "Scootering": "",
    "Ajedrez": "https://openmoji.org/data/color/svg/265F.svg",
    "Go": "",
    "Shogi": "https://openmoji.org/data/color/svg/1F004.svg",
    "Xiangqi": "",
    "Bridge": "https://openmoji.org/data/color/svg/1F0CF.svg",
    "Damas": "https://openmoji.org/data/color/svg/1F3B2.svg",
    "Póker": "https://openmoji.org/data/color/svg/1F0CF.svg",
    "Esports": "https://openmoji.org/data/color/svg/1F579.svg",
    "Cubo de Rubik": "",
    "Pelota Vasca": "",
    "Fútbol Gaélico": "https://openmoji.org/data/color/svg/26BD.svg",
    "Hurling": "",
    "Camogie": "",
    "Sepak Takraw": "",
    "Kabaddi": "",
    "Netball": "",
    "Korfball": "",
    "Floorball": "",
    "Ultimate Frisbee": "https://openmoji.org/data/color/svg/1F94F.svg",
    "Disc Golf": "",
    "Fistball": "",
    "Orientación": "",
    "Lacrosse": "",
    "Polo": "",
    "Patinaje de Velocidad sobre Ruedas": "",
    "Hockey sobre Patines": "",
    "Hockey Línea": "",
    "Patinaje Artístico sobre Ruedas": "",
    "Squash": "",
    "Raquetbol": "",
    "Vuelo a Vela / Planeador": "",
    "Acrobacia Aérea": "",
    "Tchoukball": "",
    "Bossaball": "",
    "Roller Derby": "",
    "Quidditch": "",
    "Tiro de Cuerda / Sokatira": "",
    "Carreras de Drones": "",
    "Woodchopping / Deportes de Hacheros": "",
    "Puenting": "",
    "Juegos de Fuerza": "",
    "Halterofilia / Levantamiento de Pesas": "https://openmoji.org/data/color/svg/1F4AA.svg",
    "Levantamiento de Potencia": "https://openmoji.org/data/color/svg/1F4AA.svg",
    "Culturismo": "https://openmoji.org/data/color/svg/1F4AA.svg",
    "Doma Clásica": "",
    "Salto Ecuestre": "",
    "Concurso Completo": "",
    "Enganches": "",
    "Volteo": "",
    "Enduro Ecuestre / Raid": "",
    "Reining": "",
    "Pentatlón Moderno": "",
    "Triatlón": "",
    "Duatlón": "",
    "Acuatlón": "",
    "Canicross": "",
    "Mushing / Trineo de Perros": "",
    "Patinaje sobre Hielo Sincronizado": "",
    "Bandy": "",
    "Skibobbing": "",
}
