name: Detectar Deportes con Mistral

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  detector-mistral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instala dependencias
        run: pip install requests

      - name: Ejecuta el detector mistral
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: python script_detector_mistral.py
