name: Scrape Logos

on:
  schedule:
    - cron: '0 0 * * *' # Ejecutar una vez al día a la medianoche UTC
  workflow_dispatch: # Permitir ejecución manual

jobs:
  scrape_logos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper script
        run: python script_logo.py

      - name: Commit and push logos.xml
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add logos.xml
          git commit -m 'Update logos.xml'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
