name: Actualizar Lista M3U

on:
  schedule:
    - cron: "0 * * * *"  # Ejecuta el workflow al inicio de cada hora
  workflow_dispatch:      # Permite ejecutar manualmente

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Ejecutar script de scraping
        run: python script.py

      - name: Configurar usuario de Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Commit y push de cambios
        run: |
          git add lista.m3u
          git commit -m "Actualizar lista M3U" || echo "No hay cambios para hacer commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
