name: Update M3U Playlist

on:
  schedule:
    - cron: "0 0 * * *" # Esto hará que el flujo de trabajo se ejecute una vez al día a la medianoche (hora UTC)
  workflow_dispatch: # También puede ser activado manualmente desde la interfaz de GitHub

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Verificar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Paso 3: Instalar dependencias necesarias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz

      # Paso 4: Ejecutar el script Python para actualizar la lista M3U
      - name: Run script to update M3U playlist
        run: |
          python script.py

      # Paso 5: Subir el archivo generado al repositorio
      - name: Commit and push M3U playlist
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add lista.m3u
          git commit -m "Actualizar lista M3U"
          git push
