name: update_canales_acestream.yml

on:
  schedule:
    - cron: '0 * * * *' # Ejecuta cada hora

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Run script
      run: python script_canales_acestream.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add canales_acestream.m3u
        git commit -m 'Update canales_acestream.m3u'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
