name: Update EPG

on:
  schedule:
    - cron: '0 0 * * *' # Ajusta el cron a tu preferencia
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git user
      run: |
        git config --global user.email "tutorialeswo.com"
        git config --global user.name "tutw"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Git LFS
      run: |
        sudo apt-get install -y git-lfs
        git lfs install

    - name: Run descargar_epg.py
      run: python descargar_epg.py

    - name: Track large file with Git LFS
      run: git lfs track "epg.xml"

    - name: Add and commit epg.xml
      run: |
        git add .gitattributes
        git add epg.xml
        git commit -m "Update EPG"

    - name: Push changes
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
